name: Backend Test

on:
  push:
    paths:
      - 'server/**'
      - 'docker-compose.yml'
      - '.github/workflows/backend-test.yml'
  pull_request:
    paths:
      - 'server/**'
      - 'docker-compose.yml'
      - '.github/workflows/backend-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and start backend container
      env:
        SUPABASE_URL: "https://mock.supabase.co"
        SUPABASE_KEY: "mock-key"
        SECRET_KEY: "test-secret-key"
        ALGORITHM: "HS256"
        ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      run: |
        docker-compose up -d --build

    - name: Wait for backend to be ready
      run: |
        for i in {1..30}; do
          if curl -f http://localhost:8000/docs; then
            exit 0
          fi
          sleep 1
        done
        exit 1

    - name: Check backend logs
      if: failure()
      run: docker-compose logs api 